# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/cmake-build-debug

# Include any dependencies generated for this target.
include CMakeFiles/pa01_sentiment.dir/depend.make
# Include the progress variables for this target.
include CMakeFiles/pa01_sentiment.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/pa01_sentiment.dir/flags.make

CMakeFiles/pa01_sentiment.dir/main.cpp.o: CMakeFiles/pa01_sentiment.dir/flags.make
CMakeFiles/pa01_sentiment.dir/main.cpp.o: ../main.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/pa01_sentiment.dir/main.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/pa01_sentiment.dir/main.cpp.o -c /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/main.cpp

CMakeFiles/pa01_sentiment.dir/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/pa01_sentiment.dir/main.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/main.cpp > CMakeFiles/pa01_sentiment.dir/main.cpp.i

CMakeFiles/pa01_sentiment.dir/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/pa01_sentiment.dir/main.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/main.cpp -o CMakeFiles/pa01_sentiment.dir/main.cpp.s

CMakeFiles/pa01_sentiment.dir/DSString.cpp.o: CMakeFiles/pa01_sentiment.dir/flags.make
CMakeFiles/pa01_sentiment.dir/DSString.cpp.o: ../DSString.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/pa01_sentiment.dir/DSString.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/pa01_sentiment.dir/DSString.cpp.o -c /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/DSString.cpp

CMakeFiles/pa01_sentiment.dir/DSString.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/pa01_sentiment.dir/DSString.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/DSString.cpp > CMakeFiles/pa01_sentiment.dir/DSString.cpp.i

CMakeFiles/pa01_sentiment.dir/DSString.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/pa01_sentiment.dir/DSString.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/DSString.cpp -o CMakeFiles/pa01_sentiment.dir/DSString.cpp.s

CMakeFiles/pa01_sentiment.dir/Parse.cpp.o: CMakeFiles/pa01_sentiment.dir/flags.make
CMakeFiles/pa01_sentiment.dir/Parse.cpp.o: ../Parse.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/pa01_sentiment.dir/Parse.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/pa01_sentiment.dir/Parse.cpp.o -c /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/Parse.cpp

CMakeFiles/pa01_sentiment.dir/Parse.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/pa01_sentiment.dir/Parse.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/Parse.cpp > CMakeFiles/pa01_sentiment.dir/Parse.cpp.i

CMakeFiles/pa01_sentiment.dir/Parse.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/pa01_sentiment.dir/Parse.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/Parse.cpp -o CMakeFiles/pa01_sentiment.dir/Parse.cpp.s

CMakeFiles/pa01_sentiment.dir/DSStringTest.cpp.o: CMakeFiles/pa01_sentiment.dir/flags.make
CMakeFiles/pa01_sentiment.dir/DSStringTest.cpp.o: ../DSStringTest.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/pa01_sentiment.dir/DSStringTest.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/pa01_sentiment.dir/DSStringTest.cpp.o -c /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/DSStringTest.cpp

CMakeFiles/pa01_sentiment.dir/DSStringTest.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/pa01_sentiment.dir/DSStringTest.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/DSStringTest.cpp > CMakeFiles/pa01_sentiment.dir/DSStringTest.cpp.i

CMakeFiles/pa01_sentiment.dir/DSStringTest.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/pa01_sentiment.dir/DSStringTest.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/DSStringTest.cpp -o CMakeFiles/pa01_sentiment.dir/DSStringTest.cpp.s

CMakeFiles/pa01_sentiment.dir/Words.cpp.o: CMakeFiles/pa01_sentiment.dir/flags.make
CMakeFiles/pa01_sentiment.dir/Words.cpp.o: ../Words.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object CMakeFiles/pa01_sentiment.dir/Words.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/pa01_sentiment.dir/Words.cpp.o -c /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/Words.cpp

CMakeFiles/pa01_sentiment.dir/Words.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/pa01_sentiment.dir/Words.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/Words.cpp > CMakeFiles/pa01_sentiment.dir/Words.cpp.i

CMakeFiles/pa01_sentiment.dir/Words.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/pa01_sentiment.dir/Words.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/Words.cpp -o CMakeFiles/pa01_sentiment.dir/Words.cpp.s

# Object files for target pa01_sentiment
pa01_sentiment_OBJECTS = \
"CMakeFiles/pa01_sentiment.dir/main.cpp.o" \
"CMakeFiles/pa01_sentiment.dir/DSString.cpp.o" \
"CMakeFiles/pa01_sentiment.dir/Parse.cpp.o" \
"CMakeFiles/pa01_sentiment.dir/DSStringTest.cpp.o" \
"CMakeFiles/pa01_sentiment.dir/Words.cpp.o"

# External object files for target pa01_sentiment
pa01_sentiment_EXTERNAL_OBJECTS =

pa01_sentiment: CMakeFiles/pa01_sentiment.dir/main.cpp.o
pa01_sentiment: CMakeFiles/pa01_sentiment.dir/DSString.cpp.o
pa01_sentiment: CMakeFiles/pa01_sentiment.dir/Parse.cpp.o
pa01_sentiment: CMakeFiles/pa01_sentiment.dir/DSStringTest.cpp.o
pa01_sentiment: CMakeFiles/pa01_sentiment.dir/Words.cpp.o
pa01_sentiment: CMakeFiles/pa01_sentiment.dir/build.make
pa01_sentiment: CMakeFiles/pa01_sentiment.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Linking CXX executable pa01_sentiment"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/pa01_sentiment.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/pa01_sentiment.dir/build: pa01_sentiment
.PHONY : CMakeFiles/pa01_sentiment.dir/build

CMakeFiles/pa01_sentiment.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/pa01_sentiment.dir/cmake_clean.cmake
.PHONY : CMakeFiles/pa01_sentiment.dir/clean

CMakeFiles/pa01_sentiment.dir/depend:
	cd /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/cmake-build-debug && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99 /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99 /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/cmake-build-debug /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/cmake-build-debug /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/cmake-build-debug/CMakeFiles/pa01_sentiment.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/pa01_sentiment.dir/depend

