# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/cmake-build-debug/CMakeFiles /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/cmake-build-debug//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/muhammad/Desktop/CS2341/22s-2341-pa01-MuhAsh99/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pa01_sentiment

# Build rule for target.
pa01_sentiment: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pa01_sentiment
.PHONY : pa01_sentiment

# fast build rule for target.
pa01_sentiment/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa01_sentiment.dir/build.make CMakeFiles/pa01_sentiment.dir/build
.PHONY : pa01_sentiment/fast

DSString.o: DSString.cpp.o
.PHONY : DSString.o

# target to build an object file
DSString.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa01_sentiment.dir/build.make CMakeFiles/pa01_sentiment.dir/DSString.cpp.o
.PHONY : DSString.cpp.o

DSString.i: DSString.cpp.i
.PHONY : DSString.i

# target to preprocess a source file
DSString.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa01_sentiment.dir/build.make CMakeFiles/pa01_sentiment.dir/DSString.cpp.i
.PHONY : DSString.cpp.i

DSString.s: DSString.cpp.s
.PHONY : DSString.s

# target to generate assembly for a file
DSString.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa01_sentiment.dir/build.make CMakeFiles/pa01_sentiment.dir/DSString.cpp.s
.PHONY : DSString.cpp.s

DSStringTest.o: DSStringTest.cpp.o
.PHONY : DSStringTest.o

# target to build an object file
DSStringTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa01_sentiment.dir/build.make CMakeFiles/pa01_sentiment.dir/DSStringTest.cpp.o
.PHONY : DSStringTest.cpp.o

DSStringTest.i: DSStringTest.cpp.i
.PHONY : DSStringTest.i

# target to preprocess a source file
DSStringTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa01_sentiment.dir/build.make CMakeFiles/pa01_sentiment.dir/DSStringTest.cpp.i
.PHONY : DSStringTest.cpp.i

DSStringTest.s: DSStringTest.cpp.s
.PHONY : DSStringTest.s

# target to generate assembly for a file
DSStringTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa01_sentiment.dir/build.make CMakeFiles/pa01_sentiment.dir/DSStringTest.cpp.s
.PHONY : DSStringTest.cpp.s

Parse.o: Parse.cpp.o
.PHONY : Parse.o

# target to build an object file
Parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa01_sentiment.dir/build.make CMakeFiles/pa01_sentiment.dir/Parse.cpp.o
.PHONY : Parse.cpp.o

Parse.i: Parse.cpp.i
.PHONY : Parse.i

# target to preprocess a source file
Parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa01_sentiment.dir/build.make CMakeFiles/pa01_sentiment.dir/Parse.cpp.i
.PHONY : Parse.cpp.i

Parse.s: Parse.cpp.s
.PHONY : Parse.s

# target to generate assembly for a file
Parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa01_sentiment.dir/build.make CMakeFiles/pa01_sentiment.dir/Parse.cpp.s
.PHONY : Parse.cpp.s

Words.o: Words.cpp.o
.PHONY : Words.o

# target to build an object file
Words.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa01_sentiment.dir/build.make CMakeFiles/pa01_sentiment.dir/Words.cpp.o
.PHONY : Words.cpp.o

Words.i: Words.cpp.i
.PHONY : Words.i

# target to preprocess a source file
Words.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa01_sentiment.dir/build.make CMakeFiles/pa01_sentiment.dir/Words.cpp.i
.PHONY : Words.cpp.i

Words.s: Words.cpp.s
.PHONY : Words.s

# target to generate assembly for a file
Words.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa01_sentiment.dir/build.make CMakeFiles/pa01_sentiment.dir/Words.cpp.s
.PHONY : Words.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa01_sentiment.dir/build.make CMakeFiles/pa01_sentiment.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa01_sentiment.dir/build.make CMakeFiles/pa01_sentiment.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa01_sentiment.dir/build.make CMakeFiles/pa01_sentiment.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pa01_sentiment"
	@echo "... DSString.o"
	@echo "... DSString.i"
	@echo "... DSString.s"
	@echo "... DSStringTest.o"
	@echo "... DSStringTest.i"
	@echo "... DSStringTest.s"
	@echo "... Parse.o"
	@echo "... Parse.i"
	@echo "... Parse.s"
	@echo "... Words.o"
	@echo "... Words.i"
	@echo "... Words.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

